version: '3.8'
services:
  client:
    image: keep-web
    build: ./web
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
  server:
    image: keep-backend
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - database
    env_file:
      - keep-dev.env
  database:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keep_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
    - '5432:5432'